### ISSUE TITLE
"This app can't be installed because its packages aren't compatible with this environment."

### ISSUE THREAD

**Issue by innes88** [microsoft/Templates-for-Power-Platform#13]
When I try to install the app it gives me the error "This app can't be installed because its packages aren't compatible with this environment." when I select the environment. How do I resolve this? Do I need to have the Dynamics 365 Human Resources subscription to make this work?

**Comment by Ryanb58** [comment]
Hello @innes88,

What region is the environment you are trying to install the app into?

**Comment by FTVilleP** [comment]
Same issue here, trying to install the app to a "Europe - Default" environment.

I even tried creating an environment for the United States region and enabling D365 apps but the platform doesn't allow to do so

**Comment by innes88** [comment]
Hi @Ryanb58, the environment is set in the United Kingdom region.

**Comment by dorcjill** [comment]
Same problem here. Tried environments in US, US(Preview), Australia and Europe.

**Comment by rayyjchien** [comment]
I got the same issue in environments provisioned in US and Asia.

**Comment by fly007ru** [comment]
@tshanep Hello there, what do you mean by "core" environment? "Default"? I have same issue and can't fix it now.
Session details:
Timestamp: 2023-09-28T11:09:53.914Z
Session ID: ec1d6070-5deb-11ee-a16a-f52e8242dbf7
Tenant ID: 69879a40-68bb-4b30-941b-eb9692ddd9b4
Object ID: a345e3fb-8222-4529-94d0-3a7912b27277
Build name: 0.0.20230926.3-2309.3-prod
Organization ID: b180316b-94f4-ed11-a80b-000d3a486278
Unique name: unqb180316b94f4ed11a80b000d3a486
Environment ID: 6a518375-910d-ec7b-a538-cb54a9b5cd4e
Cluster environment: Prod
Cluster category: Prod
Cluster geo name: EU
Cluster URI suffix: eu-il106.gateway.prod.island

**Comment by paragchapre** [comment]
Do you we have any pre-requisite to install this app? I tried to install on new dev environment and Dynamics 365 F&O Power platform environment but got the same error.
