### ISSUE TITLE
Will these templates be customizable?

### ISSUE THREAD

**Issue by laublarsen** [microsoft/Templates-for-Power-Platform#17]
Hi,

Currently the Kudos app is a managed solution, meaning we cannot make changes to the Email notification and other areas.

Is this going to change so that the solution will be delivered as unmanaged making it possible to customize?

[UPDATE] I have read how to modify the SAP app, by creating a new unmanaged solution and then add elements from the managed app. You can then make the changes and install both the managed app and the unmanaged app to get your own changes.
I am guessing this is the correct approach?!

**Comment by Ryanb58** [comment]
Thanks for reaching out @laublarsen. I apologize for the delayed response.

We're glad to hear that you managed to successfully implement your customizations.

We're currently collaborating with our documentation team to address this gap in information.

For future reference, please find below a link to our existing conceptual documentation. This provides a more detailed discussion on the subject matter, which could be of assistance to others encountering similar issues.

[Microsoft Power Apps Solution Layers Documentation](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/solution-layers)
