### ISSUE TITLE
Awards and Recognitions Template: Not able to create an award even I assigned myself the role of Awards and Recognition - Program Admin

### ISSUE THREAD

**Issue by subhmajumdar** [microsoft/Templates-for-Power-Platform#32]
Hi Team

I am not able to see the New option to create a new award even though I assigned my role as Awards and Recognition - Program Admin.I see the below screen which is supposed to be for a Awards and Recognition – User role I believe when I run  Awards and Recognition app. 

![image](https://github.com/microsoft/Templates-for-Power-Platform/assets/13482323/b17ebd93-5e77-441d-81cb-ceca4474d149)

**Comment by tshanep** [comment]
Thanks for the question. We've separated administrative functions from user functions. The app that you included a picture of is the user app for nominations. To adminster the program, you need to launch

**Comment by Ryanb58** [comment]
stale
