### ISSUE TITLE
SAP_Procurement Solution

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/Templates-for-Power-Platform#38]
Where can I download the solution of SAP Procurement?
In AppSource it is not available and in https://github.com/microsoft/Templates-for-Power-Platform/blob/main/DeploymentPackages/mpa_SAPProcurement/mpa_SAPProcurement.DeploymentPackage.csproj there are only scripts and there is no downloadable solution to directly import to Dataverse

**Comment by Ryanb58** [comment]
Hello @LizethRegules

Thank you for reaching out.

The solutions are built & published to the [Github Release Page located here](https://github.com/microsoft/Templates-for-Power-Platform/releases). The ones you are looking for might be a bit hidden, so please scroll the page and expand the `Assets` accordions as needed.
