### ISSUE TITLE
Not able to install Employee Kudos Template

### ISSUE THREAD

**Issue by paragchapre** [microsoft/Templates-for-Power-Platform#47]
Hi there,

I tried to install Employee Kudos Template but I received an error. I tried this in new dev environment. 

<img width="322" alt="image" src="https://github.com/microsoft/Templates-for-Power-Platform/assets/10007231/bdc8bd82-d670-4fff-b51d-451c2edd839d">

**Comment by tshanep** [comment]
Thank you for raising this issue!

While we're investigating this issue, you can alternatively install these from the Git release announcements where we have links to the managed solutions. You will need to install the base back, "EmployeeExperienceBase", before installing Kudos, Awards & Recognition, or Onboarding Buddy as they all have a dependency on that base solution. 

The releases can all be found here: https://github.com/microsoft/Templates-for-Power-Platform/releases

In addition, the latest managed solution files which you can manually import are here:

- [Employee Experience Base Solution](https://github.com/microsoft/Templates-for-Power-Platform/releases/download/0.0.7/mpa_EmployeeExperienceBase_1_0_0_12_managed.zip) 
- [Onboarding Buddy Solution](https://github.com/microsoft/Templates-for-Power-Platform/releases/download/0.0.7/mpa_OnboardingBuddy_1_0_0_11_managed.zip)
- [Awards & Recognition Solution](https://github.com/microsoft/Templates-for-Power-Platform/releases/download/0.0.3/mpa_AwardsAndRecognition_managed.zip)
- [Kudos Solution](https://github.com/microsoft/Templates-for-Power-Platform/releases/download/0.0.2/mpa_Kudos_managed.zip)

**Comment by tshanep** [comment]
The Kudos Template on AppSource has been updated so that all geos should be able to install it now. Please let us know if there continues to be issues.

Link to AppSource Kudos Template: [https://aka.ms/AccessEmployeeKudosTemplate](https://aka.ms/AccessEmployeeKudosTemplate)
