### ISSUE TITLE
Not able to install Onboarding Buddy using Appsource

### ISSUE THREAD

**Issue by sukumar83** [microsoft/Templates-for-Power-Platform#52]
Unable to install enterprise template for HR - Onboarding app using below link- https://appsource.microsoft.com/en-us/product/dynamics-365/powerplatformtemplates.mpa-onboardingbuddy
I have followed the instructions mentioned here.- https://learn.microsoft.com/en-us/power-platform/solution-templates/hr/onboarding-buddy/install-and-configure

Could you please help

**Comment by sukumar83** [comment]
I saw previous response that this is available from here - perhaps ETA when this will fix will help others -

**Comment by mhuguet** [comment]
@sukumar83, we identified an issue with our package configuration that was correct and redeployed yesterday. You should be able to install any of our templates now directly from AppSource from worldwide. Please let us know if you have any other issues and we'd love to hear if you were able to successfully install.

**Comment by tshanep** [comment]
@sukumar83 - There was some internal miscommunication - We were able to fix Kudos and Awards & Recognition, but are still working on Onboarding Buddy and the Hardware Request & Mgmt solutions. Fixes to those will be coming soon and I'll update you when those are available.

**Comment by tshanep** [comment]
@sukumar83 - The fix for Onboarding Buddy is out on AppSource now. Please let us know if you still have problems with installation. Thank you for your patience!
