### ISSUE TITLE
Hardware Request and Management template - AppPackage Error

### ISSUE THREAD

**Issue by MaxWandel** [microsoft/Templates-for-Power-Platform#58]
Hello everyone,

I've installed the Hardware Request and Management template solutions in our Dev environment and followed the steps from the learn.microsoft.com article. 
Everything works fine except for approving a request directly from the Model Driven App request form. I am getting the following error:

**Exception Message: AppLogicalName mpa_HardwareRequestAdministrator_DefaultCommandLibrary does not have an AppPackage**
ErrorCode: -2147015419
HexErrorCode: 0x80072505
Error Details: AppLogicalName mpa_HardwareRequestAdministrator_DefaultCommandLibrary does not have an AppPackage

![image](https://github.com/microsoft/Templates-for-Power-Platform/assets/117990866/1864ec72-aede-46dc-84ed-a90277b118cc)

What am I missing in the setup? Can somebody give me an advice how to handle this error?

Cheers,
Max

**Comment by robinsonshields** [comment]
There is a new version of the Hardware Request and Management template. Please download the new version and install. Thank you.

**Comment by aherronclarecoco** [comment]
I'm also getting this error but only installed the template last week, any help would be appreciated!
