### ISSUE TITLE
Unable to install to GCC

### ISSUE THREAD

**Issue by Yocomd** [microsoft/Templates-for-Power-Platform#62]
I am unable to install the Kudos template to a GCC environment from AppSource.  Is there some way that I can just get the solution.zip file to install it myself?

**Comment by galitskyd** [comment]
You should be able to download the zip files under the releases tab. Here is a link: https://github.com/microsoft/Templates-for-Power-Platform/releases/tag/0.0.9

**Comment by mhuguet** [comment]
@Yocomd, were you able to install the solution?
