### ISSUE TITLE
Unable to turn on the "CreateRequisition" fLow in SAP Procurement Solution Template

### ISSUE THREAD

**Issue by iSK101** [microsoft/Templates-for-Power-Platform#69]
Unable to turn on the "CreateRequisition" fLow in SAP Procurement Solution Template. 

Error : Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'WorkflowOperationParametersExtraParameter' and message 'The API operation does not contain a definition for parameter 'rfcInputs/PRHEADER/PR_TYPE'.'."}}".

![image](https://github.com/microsoft/Templates-for-Power-Platform/assets/171793932/307e8018-2285-46ca-99f9-371ced0fcb81)

**Comment by mhuguet** [comment]
We apologize for the delay. We are looking into this issue. We do have a newer version of the cloud flows we are publishing in the near future where this should be addressed. We will leave this open until you can confirm that you are no longer experiencing this issue.

**Comment by microsoft-george** [comment]
As stated above, a corrected version of the cloud flow should be published in the near future. To unblock right now here are the steps to correct:
1. Create an unmanaged version of the flow
2. Initialize the following variables
    - Name: `PRHEADER` value: `{"PR_TYPE": "NB"}`
    - Name: `PRHEADERX` value `{"PR_TYPE": "X"}`
3. In Step: `BAPI_PR_CREATE`, replace values in `rfcInputs/PRHEADER` and `rfcInputs/PRHEADERX` with the corresponding variables above

**Comment by mhuguet** [comment]
Closing as we have released an update with this being addressed. https://github.com/microsoft/Templates-for-Power-Platform/releases/tag/v2.0
