### ISSUE TITLE
Issue while importing template and turning on the flow for Create Requisition

### ISSUE THREAD

**Issue by onecaregetz** [microsoft/Templates-for-Power-Platform#71]
getting below error while importing template and turning on the flow for Create Requisition and Update Requisition 

![image](https://github.com/user-attachments/assets/4c458247-d690-47bf-8893-e5077f7f833a)
![image](https://github.com/user-attachments/assets/1c0266e0-6ff3-4376-b04f-9263a5e3fff1)

**Comment by mhuguet** [comment]
We apologize for the delay. We are looking into this issue. We do have a newer version of the cloud flows we are publishing in the near future where this should be addressed.

**Comment by mhuguet** [comment]
We will leave this open until you can confirm it is addressed for you.

**Comment by microsoft-george** [comment]
A workaround for this issue is described here #69 Please follow steps to unblock.

**Comment by mhuguet** [comment]
Closing this as we have a new release that addresses this. https://github.com/microsoft/Templates-for-Power-Platform/releases/tag/v2.0
