### ISSUE TITLE
Installation failed: Hardware Request and Management Template

### ISSUE THREAD

**Issue by selimdag** [microsoft/Templates-for-Power-Platform#87]
The installation fails In Hardware Request and Management Template with the error message: "Import failed: User impersonation mode is not supported" 
I tried it in different tenants and environments but getting every time the same error. 

![image](https://github.com/user-attachments/assets/81ede9ab-4554-47b5-bac5-b0c540b616ef)

**Comment by jaev2412** [comment]
I am having the same issue. Anyone is looking at it? 

![Image](https://github.com/user-attachments/assets/6fb7e901-7c16-4cb2-9461-eed07775d3cd)

**Comment by ramanasridhar** [comment]
Sorry for the late response. We are looking at this and will provide an update soon. Thanks.

**Comment by deepthimk123** [comment]
@jaev2412 @selimdag the issue has been resolved, and you can now install the latest from the offer center or fetch latest from the GitHub code repository. Kindly confirm if I can close the issue.
