### ISSUE TITLE
Installation Error: Hardware Request And Management re: PowerBi component retirement

### ISSUE THREAD

**Issue by CKJonesy** [microsoft/Templates-for-Power-Platform#94]
Error code
[8004801E](http://go.microsoft.com/fwlink/?LinkID=398563&client=Solutions&Error=8004801E&de=online)
Exception message
Import failed: Power BI content management has reached retirement. We recommend removing all Power BI report and dataset components from existing solutions and use Power BI embedded system dashboard

Tried appsource and manual installs. Presume the solution needs an update?

**Comment by deepthimk123** [comment]
Hi @CKJonesy, we are actively working on this issue and will provide an update as soon as possible.

**Comment by Atleastihaveme** [comment]
Hello @deepthimk123 , I have a customer encountering this issue as well, could you please kindly share if this a known issue for now? Thank you.

**Comment by Atleastihaveme** [comment]
Hello @deepthimk123 , could you please kindly share if there is any fix process update of this issue for now? Thank you! The customer is waiting for install this app. And found this document which may be related to this issue: https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/power-bi-content-management-power-apps-solutions.

**Comment by deepthimk123** [comment]
@Atleastihaveme The issue has been resolved, and you can now install the latest from the offer center or fetch latest from the GitHub code repository.
